namespace DataGen {
    // ReSharper disable UnusedMember.Global
    /// <summary>
    ///  Is used for Filtering by country
    /// </summary>
    public enum Country {
        CostaRica,
        ElSalvador,
        Guatemala,
        Albania,
        Austria,
        Azerbaijan,
        Belgium,
        Croatia,
        Czech,
        Denmark,
        Estonia,
        FaroeIslands,
        Finland,
        France,
        Germany,
        Greece,
        Hungary,
        Ireland,
        Italy,
        Latvia,
        Luxembourg,
        Macedonia,
        Malta,
        Moldova,
        Netherlands,
        Norway,
        Poland,
        Portugal,
        Romania,
        Russia,
        Slovakia,
        Slovenia,
        Spain,
        Sweden,
        Switzerland,
        Turkey,
        Ukraine,
        UnitedKingdom,
        Canada,
        Cuba,
        Mexico,
        UnitedStates,
        Argentina,
        Brazil,
        Paraguay
    }
}