configuration: Release

init:
    - ps: modelinex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

before_build:
  - nuget restore

build:
  parallel: true
  verbosity: minimal

on_success:
- ps: '& ".\deployment.ps1"'

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
