version: '1.0.{build}'
image: Visual Studio 2017
#branches:
#  only:
#  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  #- cmd: dotnet restore --verbosity m
  - cmd: nuget restore
build_script:
  - cmd: dotnet build .\src\GeneratorAPI\GeneratorAPI.csproj -c Release
  - cmd: dotnet msbuild .\src\Sharpy\Sharpy.csproj /p:Configuration=Release
  - cmd: dotnet msbuild .\Tests\Tests.csproj /p:Configuration=Release
after_build:
  # For once the build has completed
clone_depth: 1
test_script:
  # restore packages for our unit tests
  #- cmd: dotnet restore ./tests/tests.csproj --verbosity m
  # Install the unit test runner
  - nuget install NUnit.ConsoleRunner -Version 3.7.0  -o consolerunner
  # Run the unit test runner
  - cmd: .\consolerunner\NUnit.ConsoleRunner.3.7.0\tools\nunit3-console.exe .\tests\bin\Release\Tests.dll
on_finish :
  # any cleaup in here
deploy_script:
  - cmd: powershell -File .\deployment.ps1
