name: Generate DocFx
on: [push]

jobs:
  DocFx:
    runs-on: ubuntu-latest
    name: Deploy DocFx to GH pages
    steps:
      - uses: actions/checkout@v2
      - uses: nikeee/docfx-action@v1.0.0
        name: Build Documentation
        with:
          args: ./docs/docfx.json

      # Publish generated site using GitHub Pages
      - uses: maxheld83/ghpages@master
        name: Publish Documentation on GitHub Pages
        if: success() && github.ref == 'refs/heads/master'
        env:
          BUILD_DIR: ./docs/_site # docfx's default output directory is _site
          GH_PAT: ${{ secrets.GH_PAT }} # See https://github.com/maxheld83/ghpages
